FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.pipeline.txt .
RUN pip install --no-cache-dir -r requirements.pipeline.txt

# Copy pipeline package
COPY pipeline /app/pipeline

CMD ["python", "pipeline/detect.py"]
